- src/FrontEnd/IntermediateCode/fe_intermediate_code.py
Only one file added; describes the Intermediaite Code generated by the Scanner and provided as ipunt to the Parser of Typee Front-End.
> #19-Front End InterM.Code - Intermediate Code

- src/Tests/Documentation-README/scanner_tokenization_tests.md
Added a new sub-directory `Documentation-README` in `src/Tests` and put the Front-End scanner testing documentation in it : MD file `scanner_tokenization_tests.md`.
> #24- Front-End Scanner Tesing - documentation

- src/Tests/Documentation-README/scanner_tokenization_tests.md
- src/_Global_Documentation/__main_index.md
- Created the related directory;
- created the very first revision of the main index.
> #32-Create Global Documentation for Typee software documentation

- src/FrontEnd/Scanner/fe_scanner.py
Not that long to complete. All ICNode_XXX class names are now renamed with their new name ICTokenNode_XXX
> #35-Correct Scanner Code

- .pydevproject
Enamed directory inserting "HTML" in it.
> #45-Typee Global S/W Architecture Documentation

- _Global_Documentation/programming-languages-translation-State-of-the-Art.md
Completed sections 1. and 2. of document "state of the art on programming languages translation.md"
> #81 state of the art on programming languages translation

- _Global_Documentation/programming-languages-translation-State-of-the-Art.md
Completed section 3.;
Added section 4.;
Document needs now reviewing
> #81-State of the Art on Programming Languages

- src/Libs/Time/time.ty
Module time.ty in lib Time: created from scratch. Embeds Python, C++, Java and Java-Android.
> #96-Typee built in library Time

- src/Libs/Files/base_file.ty
- src/Libs/Files/f_types.ty
- src/Libs/Files/r_file.ty
- src/Libs/Files/ro_file.ty
- src/Libs/Files/rw_file.ty
- src/Libs/Files/w_file.ty
- src/Libs/Files/wo_file.ty
- src/Libs/SysTime/systime.ty
> #112-Files built-in Typee library.

- src/Libs/Thread/barrier.ty
- src/Libs/Thread/base_thread.ty
- src/Libs/Thread/condition.ty
- src/Libs/Thread/daemon_thread.ty
- src/Libs/Thread/event.ty
- src/Libs/Thread/latch.ty
- src/Libs/Thread/lockable.ty
- src/Libs/Thread/semaphore.ty
- src/Libs/Thread/thread_exceptions.ty
- src/Libs/Thread/timer.ty
First implementation completed with sole Python embedded code.
> #126 thread built in typee library implementation

- src/Libs/Thread/base_thread.ty
- src/Libs/Thread/daemon_thread.ty
- Added Java code to modules `base_thread.ty` and `daemon_thread.ty`.
> #126-Thread built-in Typee library implementation

- Language-specifications/typee_specs_LL1-v9-EBNF.grm
- Language-specifications/typee_specs_LL1-v9.grm
Done. We can now delete this branch.
> #86-Create Extended BNF document for Typee grammar specification

- Language-specifications/typee_specs_LL1-v9-EBNF.grm
- Language-specifications/typee_specs_LL1-v9.grm
- src/Libs/Thread/base_thread.ty
Synchronization with master branch about versions v9 and v9-EBNF of Typee grammar specifications document.
> #85 modify / correct typee syntax

- src/FrontEnd/Parser/fe_parser.py
Added code related to new version v9.1 of Typee syntax.
> #150-Modify-Correct Parser Code

- src/Libs/Thread/base_thread.ty
- src/Libs/Thread/daemon_thread.ty
- src/Libs/Thread/thread_barrier.ty
- src/Libs/Thread/thread_condition.ty
- src/Libs/Thread/thread_event.ty
- src/Libs/Thread/thread_guarded_block.ty
- src/Libs/Thread/thread_guarded_var.ty
- src/Libs/Thread/thread_latch.ty
- src/Libs/Thread/thread_mutex.ty
- src/Libs/Thread/thread_semaphore.ty
- src/Libs/Thread/thread_timer.ty
- src/Libs/Thread/thread_watchdog.ty
First review of `Thread` built-in library code. Lead to modifications and fixes.
> #141-Thread library validation

- src/Libs/SysTime/perfmeter.ty
- src/Libs/SysTime/systime.ty
Code review completed. Modifications done.
> #142-SysTime library validation-built-in Typpe libraries

- src/Libs/Random/Bases/base_lcg.ty
- src/Libs/Random/Bases/base_lfib64.ty
- src/Libs/Random/Bases/base_mrg.ty
- src/Libs/Random/Bases/base_rand_state.ty
- src/Libs/Random/Bases/base_random.ty
- src/Libs/Random/rand116.ty
- src/Libs/Random/rand1340.ty
- src/Libs/Random/rand1457.ty
- src/Libs/Random/rand287.ty
- src/Libs/Random/rand32.ty
- src/Libs/Random/rand49507.ty
- src/Libs/Random/rand63.ty
- src/Libs/Random/rand668.ty
- src/Libs/Random/rand78.ty
Code review completed. Modifications and fixes done.
> #143-Random library validation - built-in Typee libraries

- src/Libs/Random/rand63.ty
Fixed two bugs while code-reviewing in class `Rand63` - module `Libs/Random/rand63.ty`.
> #143-Random library validation

- Language-specifications/typee_specs_LL1-v9-3-EBNF.grm
- Language-specifications/typee_specs_LL1-v9-3.grm
Fixed a definition bug in rule <atom element> and its derivations.
> #85-Modify/Coorrect Typee Syntax

- Language-specifications/typee_specs_LL1-v9-3-EBNF.grm
- Language-specifications/typee_specs_LL1-v9-3.grm
Added PHP operator `<=>` to Typee syntax
> #85-Modify / Correct Typee syntax

- README.md
> #223 - Modify/Correct global documentation

- src/Commons/access.py
- src/FrontEnd/Elaborator/fe_elaborator.py
- src/FrontEnd/Elaborator/fe_symbols_elaborator.py
- src/FrontEnd/Elaborator/fe_types_elaborator.py
- src/FrontEnd/IntermediateCode/fe_icblock.py
- src/FrontEnd/IntermediateCode/fe_icleaf.py
- src/FrontEnd/IntermediateCode/fe_icnode.py
- src/FrontEnd/IntermediateCode/fe_icode_tokens.py
- src/FrontEnd/IntermediateCode/fe_ictree.py
- src/FrontEnd/Parser/fe_parser.py
- src/FrontEnd/Scanner/fe_scanner.py
- src/Tests/FrontEnd/IntermediateCode/script_ic_tree.py
- src/Tests/FrontEnd/Scanner_Tokens/Data/tokenization_simple_solution.py
- src/Tests/FrontEnd/Scanner_Tokens/test_compound_tokens.py
- src/Tests/FrontEnd/Scanner_Tokens/test_names_and_nums_tokens.py
- src/Tests/FrontEnd/Scanner_Tokens/test_simple_tokens.py
- src/Tests/FrontEnd/Scanner_Tokens/tokens_test_base.py
- src/Utils/ut_serialized_enum.py
- src/Utils/ut_tree.py
- src/local_tools/copyright_years_modif.py
- src/local_tools/template_class.py
- src/local_tools/tool_generate_feicode_token_node_module.py
> #227- Modify existing source to conform with Python PEP 484

- src/FrontEnd/IntermediateCode/fe_icblock.py
- src/FrontEnd/IntermediateCode/fe_icnode.py
- src/Tests/Utils/script_ut_tree.py
A few commits on branch `master`...
Have to merge branch `dev` now...
> merge master and dev branch

- README.md
> #223-Modify/Correct global documentation

- src/Libs/types.ty
Modifiied the presentation of types aliases in module `Libs/types.ty`. Easier to read now.
> #267-Modify / Correct Typee built-in code

- src/Libs/Thread/utils/utils.ty
Augmented code for module `Libs.Thread.utils.utils.ty`. with a try-except clause.
> #141-Thread library validation - built-in Typee library

- src/Libs/Files/base_file.ty
- src/Libs/Files/r_file.ty
- Fixed a naming bug in module `Libs.Files.base_file.ty`;
- Fixed missing code in module `Libs.Files.r_file.ty`.
> #104-Correct / Modify Built-in Libraries
